// <auto-generated />
namespace NakedIdentity.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class changeemailtousername : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeemailtousername));
        
        string IMigrationMetadata.Id
        {
            get { return "201912080608517_change email to username"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
